### ISSUE TITLE
World DMG 

### ISSUE THREAD

**Issue by benk0913** [Tzook/lul#113]
An event / alternative so the client could say " I stepped on a spike / lava / etc..." and get hurt.

**Comment by Tzook** [comment]
@benk0913 we can use the existing mobs infrastructure to do that. this way we can also utilize the perks of the mob and even spells.
Just need to add a small indication that this mob cannot take damage.
What do you think?

**Comment by benk0913** [comment]
No, mob dmg with perks is different. We need specifixly world events because these events are not caused via spawning and syepling on a monster

**Comment by Tzook** [comment]
Let's remember to talk about this
