### ISSUE TITLE
healing quest condition bugged.

### ISSUE THREAD

**Issue by benk0913** [Tzook/lul#154]
Can't place the quest key as "type"  for quest condition because the server is returning that it can parse it to a number.
Also, the quest doesn't progress when I heal other players (In case I use no key for the type.)

@Tzook

**Comment by Tzook** [comment]
Nono, it should be something like this:
`{condition: {condition: "heal", conditionType: ""}}`

**Comment by benk0913** [comment]
@Tzook  Still bugged... for some reason the heals wont add up to the progress...

**Comment by Tzook** [comment]
@benk0913 the healing adds up just fine (I see the DB values being incremented).
There's no issue at all, it just wasn't implemented in the client. See https://github.com/Tzook/lel/issues/346.
