### ISSUE TITLE
Quests - jaxdox

### ISSUE THREAD

**Issue by Tzook** [Tzook/lul#36]

**Comment by Tzook** [comment]
https://docs.google.com/document/d/1nR84J6jPV4iiTIRH5bDUEQfZSU7oQMxTxyOKGgmBv5w/edit#bookmark=kix.uy9bnbswow6s

**Comment by benk0913** [comment]
@Tzook  Are you sure this issue should be closed? Theres still the conditions unfinished and the quests are not given on start :o or do they?

**Comment by Tzook** [comment]
@benk0913 make sure that quests conditions have either "hunt" or "loot" in their "condition" field in the content god.
