### ISSUE TITLE
Party / Group

### ISSUE THREAD

**Issue by benk0913** [Tzook/lul#49]
Players may invite other players to a party in one of the following cases: 
*not in party and other player is not in party too (Otherwise will send the client a message) 
*in party and leader, and other player is not in party 
(otherwise blabla etc... same shit)

*Leader may remove players from party

Party limit = 5ppl? 
Should discuss this, why 5? Why not 7 for example? (Maybe because of dungeons)

*Exp gained from a party member via  mob should be shared with party members (in the same room) equally!

*Loot, unprevented from a party member should be unprevented from party members aswell.

*Gold should be shared equally on the same terms as exp (Same room, etc...)

*Party members should recieve (ActorGotDamaged [not the correct name] ) - event for party members
So other players could see the current HP of a companion.

*People should "accept" party invitations (otherwise not in party) which could be resent / become irrelevant after 30 seconds. (Maybe an other approach? Should discuss)

*Players may leave party in any time.

*If the leader leaves a party, the next player in the party recieves leadership.

*A player which logs in and is still within a party should be updated with the party members (Names?)

*Players should be informed that an other player was added / left the party.

*Optional - Party has an additional different chat

HOPEFULLY COVERED ALL CASES :p

**Comment by Tzook** [comment]
Nicely done boss!
