### ISSUE TITLE
Not recieving known character "LoggedOut" when party member logs out...

### ISSUE THREAD

**Issue by benk0913** [Tzook/lul#69]

**Comment by Tzook** [comment]
I'm seeing this event being sent.
See attached image.
<img width="825" alt="screen shot 2017-07-09 at 18 36 40" src="https://user-images.githubusercontent.com/7537694/27995400-6f29b60a-64d6-11e7-9094-a2fab0b32bd7.png">

**Comment by Tzook** [comment]
@benk0913 There was an extra space in the event name in the client =p

**Comment by benk0913** [comment]
@Tzook  supreme lelz ><
