### ISSUE TITLE
Quest won't complete (Not enough inv space even tho there is)

### ISSUE THREAD

**Issue by benk0913** [Tzook/lul#87]
When trying to complete "examineLostSupplies" quest it gives 5 items as reward, the character "KEKINA" has enough slots to pick them all up but for some reason the server says "No fuck u u need 5 slots" BUT THERE ARE FREE SLOTS...
 w/e
bug, I  think...

@Tzook

**Comment by Tzook** [comment]
Good catch, @benk0913.
